name: Docker Compose Multi-Arch Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          use: true

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Vue app
        uses: docker/build-push-action@v2
        with:
          context: ./client
          push: true
          platforms: linux/amd64,linux/arm64
          tags: your-dockerhub-username/vue-app:latest
          build-args: |
            VUE_APP_API_URL=${{ secrets.VUE_APP_API_URL }}

      - name: Build and push Node server
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          platforms: linux/amd64,linux/arm64
          tags: your-dockerhub-username/node-server:latest
          build-args: |
            SPREADSHEET_ID=${{ secrets.SPREADSHEET_ID }}
            GOOGLE_APPLICATION_CREDENTIALS_JSON=${{ secrets.GOOGLE_CREDENTIALS_JSON }}
